import { KEYS, readKey, writeKey } from "./storage";
import type { Product, User } from "./types";

// Curated Unsplash product imagery (stable hot-linked URLs).
const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEMO_USERS: User[] = [
  {
    id: "u-admin",
    name: "Aarav Admin",
    email: "gkj82003@gmail.com",
    password: "123456789",
    role: "admin",
    status: "active",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u-vendor-1",
    name: "Maya Sharma",
    email: "jhag82003@gmail.com",
    password: "123456789",
    role: "vendor",
    status: "active",
    shopName: "Sunset Threads",
    address: "12 Linking Road, Mumbai",
    phone: "+91 98200 12345",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u-vendor-2",
    name: "Ravi Kapoor",
    email: "vendor2@shopeasy.com",
    password: "123456789",
    role: "vendor",
    status: "active",
    shopName: "Slate Electronics Co.",
    address: "44 MG Road, Bengaluru",
    phone: "+91 98456 22113",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u-customer-1",
    name: "Priya Verma",
    email: "customer@shopeasy.com",
    password: "123456789",
    role: "customer",
    status: "active",
    address: "B-203, Lotus Heights, Pune",
    phone: "+91 98765 43210",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u-customer-2",
    name: "Arjun Nair",
    email: "jhagaurav82003@gmail.com",
    password: "123456789",
    role: "customer",
    status: "active",
    address: "9th Cross, Indiranagar, Bengaluru",
    phone: "+91 99887 65432",
    createdAt: new Date().toISOString(),
  },
];

const now = () => new Date().toISOString();

export const DEMO_PRODUCTS: Product[] = [
  // Electronics — vendor 2
  {
    id: "p-1", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Aurora Wireless Earbuds Pro",
    description: "Hybrid ANC, 32-hour battery life and crystal-clear hi-fi sound. Designed for all-day comfort with adaptive ear-tip sizing.",
    specifications: "Driver: 11mm dynamic\nBattery: 8h + 24h case\nBluetooth: 5.3\nWeight: 4.6g per bud",
    price: 4999, discount: 20, stock: 24, category: "Electronics", subCategory: "Audio",
    colors: ["Slate", "Sunset", "Ivory"], sizes: [],
    images: [img("photo-1606220588913-b3aacb4d2f46"), img("photo-1590658268037-6bf12165a8df")],
    rating: 4.6, ratingCount: 218, createdAt: now(),
  },
  {
    id: "p-2", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Helios Smart Watch Series 5",
    description: "AMOLED always-on display, advanced health tracking and a 14-day battery. Built from recycled aluminium.",
    specifications: "Display: 1.43\" AMOLED\nBattery: 14 days\nWater: 5 ATM\nGPS: Dual-band",
    price: 12999, discount: 15, stock: 8, category: "Electronics", subCategory: "Wearables",
    colors: ["Graphite", "Sunset Gold"], sizes: [],
    images: [img("photo-1546868871-7041f2a55e12"), img("photo-1579586337278-3befd40fd17a")],
    rating: 4.5, ratingCount: 142, createdAt: now(),
  },
  {
    id: "p-3", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Nova X1 Smartphone",
    description: "6.7-inch fluid AMOLED, triple-camera system with 50MP main sensor, and a Snapdragon flagship chip.",
    specifications: "Display: 6.7\" 120Hz\nRAM: 12GB / Storage: 256GB\nCamera: 50MP + 12MP + 8MP\nBattery: 5000 mAh",
    price: 54999, discount: 10, stock: 0, category: "Electronics", subCategory: "Mobile",
    colors: ["Midnight", "Sunset Red"], sizes: [],
    images: [img("photo-1511707171634-5f897ff02aa9"), img("photo-1592750475338-74b7b21085ab")],
    rating: 4.7, ratingCount: 389, createdAt: now(),
  },
  {
    id: "p-4", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Echo Studio Bluetooth Speaker",
    description: "Room-filling 360° sound with deep bass and an elegant fabric-wrapped enclosure. 18-hour battery.",
    specifications: "Output: 30W\nBattery: 18h\nIPX rating: IPX5\nAux + USB-C",
    price: 7499, discount: 25, stock: 14, category: "Electronics", subCategory: "Audio",
    colors: ["Charcoal", "Sand"], sizes: [],
    images: [img("photo-1608043152269-423dbba4e7e1"), img("photo-1545454675-3531b543be5d")],
    rating: 4.4, ratingCount: 87, createdAt: now(),
  },
  {
    id: "p-5", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Pulse Fit Tracker Lite",
    description: "Lightweight fitness band with heart-rate, SpO2 and sleep tracking — water resistant up to 50m.",
    specifications: "Display: 1.1\" AMOLED\nBattery: 10 days\nWater: 5 ATM",
    price: 2499, discount: 30, stock: 42, category: "Electronics", subCategory: "Wearables",
    colors: ["Black", "Sunset", "Olive"], sizes: [],
    images: [img("photo-1557935728-e6d1eaabe558"), img("photo-1508685096489-7aacd43bd3b1")],
    rating: 4.2, ratingCount: 56, createdAt: now(),
  },
  {
    id: "p-6", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Lumen Pro Mirrorless Camera",
    description: "24MP full-frame mirrorless with in-body stabilization and 4K60 video. Built for storytellers.",
    specifications: "Sensor: 24MP full-frame\nVideo: 4K60\nIBIS: 5-axis\nWeight: 658g",
    price: 89999, discount: 8, stock: 3, category: "Electronics", subCategory: "Audio",
    colors: ["Black"], sizes: [],
    images: [img("photo-1510127034890-ba27508e9f1c"), img("photo-1502920917128-1aa500764cbd")],
    rating: 4.8, ratingCount: 211, createdAt: now(),
  },
  {
    id: "p-7", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Skyline Tablet 11",
    description: "11-inch laminated display, M-class chip and all-day battery. Perfect for sketching and productivity.",
    specifications: "Display: 11\" 2.5K\nStorage: 128GB\nBattery: 10h",
    price: 32999, discount: 12, stock: 0, category: "Electronics", subCategory: "Mobile",
    colors: ["Silver", "Slate"], sizes: [],
    images: [img("photo-1544244015-0df4b3ffc6b0"), img("photo-1561154464-82e9adf32764")],
    rating: 4.3, ratingCount: 71, createdAt: now(),
  },

  // Fashion — vendor 1
  {
    id: "p-8", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Terracotta Linen Shirt",
    description: "Hand-loomed pure linen in a relaxed fit. Breathable, sustainably made, perfect for warm afternoons.",
    specifications: "Fabric: 100% linen\nFit: Relaxed\nCare: Cold wash, line dry",
    price: 2499, discount: 15, stock: 30, category: "Fashion",
    colors: ["Terracotta", "Sand", "Olive"], sizes: ["S", "M", "L", "XL", "XXL"],
    images: [img("photo-1602810318383-e386cc2a3ccf"), img("photo-1620799140408-edc6dcb6d633")],
    rating: 4.5, ratingCount: 98, createdAt: now(),
  },
  {
    id: "p-9", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Slate Wool Overcoat",
    description: "Tailored long overcoat in a refined slate wool blend. A timeless silhouette for every winter.",
    specifications: "Fabric: 70% wool, 30% poly\nLining: Cupro\nCare: Dry clean only",
    price: 8999, discount: 20, stock: 12, category: "Fashion",
    colors: ["Slate", "Charcoal"], sizes: ["S", "M", "L", "XL"],
    images: [img("photo-1591047139829-d91aecb6caea"), img("photo-1539109136881-3be0616acf4b")],
    rating: 4.7, ratingCount: 64, createdAt: now(),
  },
  {
    id: "p-10", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Sunset Cotton Tee",
    description: "Mid-weight organic cotton tee with a soft-washed finish. Cut for an easy, modern fit.",
    specifications: "Fabric: Organic cotton 220 gsm\nFit: Regular",
    price: 999, discount: 10, stock: 80, category: "Fashion",
    colors: ["Sunset", "Ivory", "Slate", "Olive"], sizes: ["S", "M", "L", "XL", "XXL"],
    images: [img("photo-1521572163474-6864f9cf17ab"), img("photo-1527719327859-c6ce80353573")],
    rating: 4.4, ratingCount: 312, createdAt: now(),
  },
  {
    id: "p-11", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Dune Wide-Leg Trousers",
    description: "Flowing wide-leg trousers in a textured tencel weave. Effortless tailoring with a relaxed drape.",
    specifications: "Fabric: Tencel blend\nFit: Wide-leg, high-rise",
    price: 3499, discount: 18, stock: 22, category: "Fashion",
    colors: ["Dune", "Slate", "Black"], sizes: ["S", "M", "L", "XL"],
    images: [img("photo-1594633312681-425c7b97ccd1"), img("photo-1473966968600-fa801b869a1a")],
    rating: 4.3, ratingCount: 41, createdAt: now(),
  },
  {
    id: "p-12", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Ember Knit Cardigan",
    description: "Chunky merino-blend cardigan with a structured collar and tortoiseshell buttons.",
    specifications: "Fabric: Merino blend\nCare: Hand wash cold",
    price: 4299, discount: 22, stock: 0, category: "Fashion",
    colors: ["Ember", "Cream"], sizes: ["S", "M", "L", "XL"],
    images: [img("photo-1434389677669-e08b4cac3105"), img("photo-1525507119028-ed4c629a60a3")],
    rating: 4.6, ratingCount: 73, createdAt: now(),
  },
  {
    id: "p-13", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Marigold Silk Scarf",
    description: "Hand-rolled mulberry silk scarf with a marigold botanical print. A luminous accessory for any season.",
    specifications: "Fabric: 100% mulberry silk\nSize: 90 x 90 cm",
    price: 1899, discount: 12, stock: 18, category: "Fashion",
    colors: ["Marigold", "Indigo"], sizes: ["S"],
    images: [img("photo-1601925260368-ae2f83cf8b7f"), img("photo-1601924994987-69e26d50dc26")],
    rating: 4.5, ratingCount: 29, createdAt: now(),
  },
  {
    id: "p-14", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Harvest Denim Jacket",
    description: "Classic trucker silhouette in 13oz selvedge denim with copper rivets and a relaxed fit.",
    specifications: "Fabric: 13oz selvedge denim\nHardware: Copper",
    price: 5499, discount: 18, stock: 16, category: "Fashion",
    colors: ["Indigo", "Sand"], sizes: ["S", "M", "L", "XL", "XXL"],
    images: [img("photo-1543076447-215ad9ba6923"), img("photo-1551537482-f2075a1d41f2")],
    rating: 4.4, ratingCount: 88, createdAt: now(),
  },

  // Footwear — vendor 1
  {
    id: "p-15", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Trailblazer Suede Sneakers",
    description: "Premium suede uppers on a cushioned EVA midsole. Designed for city days and weekend escapes.",
    specifications: "Upper: Suede\nMidsole: EVA\nOutsole: Rubber",
    price: 4799, discount: 15, stock: 25, category: "Footwear",
    colors: ["Sunset", "Olive", "Cream"], sizes: ["7", "8", "9", "10", "11", "12"],
    images: [img("photo-1542291026-7eec264c27ff"), img("photo-1600185365926-3a2ce3cdb9eb")],
    rating: 4.6, ratingCount: 154, createdAt: now(),
  },
  {
    id: "p-16", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Canyon Leather Boots",
    description: "Full-grain leather Chelsea boots with a Goodyear-welted sole. Built to last, made to age.",
    specifications: "Upper: Full-grain leather\nConstruction: Goodyear welt",
    price: 8999, discount: 10, stock: 9, category: "Footwear",
    colors: ["Tan", "Black"], sizes: ["7", "8", "9", "10", "11"],
    images: [img("photo-1520639888713-7851133b1ed0"), img("photo-1605733513597-a8f8341084e6")],
    rating: 4.7, ratingCount: 76, createdAt: now(),
  },
  {
    id: "p-17", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Drift Performance Runners",
    description: "Featherweight runners with a responsive carbon plate and a breathable engineered mesh upper.",
    specifications: "Drop: 8mm\nWeight: 220g\nPlate: Carbon",
    price: 6499, discount: 20, stock: 0, category: "Footwear",
    colors: ["Slate", "Sunset"], sizes: ["8", "9", "10", "11", "12"],
    images: [img("photo-1542291026-7eec264c27ff"), img("photo-1595950653106-6c9ebd614d3a")],
    rating: 4.5, ratingCount: 132, createdAt: now(),
  },
  {
    id: "p-18", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Meadow Strap Sandals",
    description: "Hand-stitched leather sandals with a contoured cork footbed. Comfort that softens with every step.",
    specifications: "Upper: Vegetable-tanned leather\nFootbed: Cork",
    price: 3299, discount: 12, stock: 33, category: "Footwear",
    colors: ["Tan", "Olive"], sizes: ["7", "8", "9", "10", "11"],
    images: [img("photo-1603487742131-4160ec999306"), img("photo-1603487742131-4160ec999306")],
    rating: 4.3, ratingCount: 47, createdAt: now(),
  },
  {
    id: "p-19", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Loft Loafers",
    description: "Hand-finished penny loafers in supple Italian leather with a soft leather lining.",
    specifications: "Upper: Italian leather\nLining: Leather",
    price: 7299, discount: 14, stock: 11, category: "Footwear",
    colors: ["Cognac", "Black"], sizes: ["8", "9", "10", "11"],
    images: [img("photo-1614252369475-531eba835eb1"), img("photo-1533867617858-e7b97e060509")],
    rating: 4.4, ratingCount: 38, createdAt: now(),
  },
  {
    id: "p-20", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Summit Hiking Boots",
    description: "Waterproof Nubuck uppers, Vibram outsoles and a roomy toe box. Trail-ready, city-proven.",
    specifications: "Waterproof: Yes\nOutsole: Vibram\nWeight: 480g",
    price: 9999, discount: 18, stock: 7, category: "Footwear",
    colors: ["Brown", "Slate"], sizes: ["8", "9", "10", "11", "12"],
    images: [img("photo-1542838132-92c53300491e"), img("photo-1551107696-a4b0c5a0d9a2")],
    rating: 4.6, ratingCount: 92, createdAt: now(),
  },
  {
    id: "p-21", vendorId: "u-vendor-1", vendorName: "Slate Electronics Co.",
    name: "Halo Over-Ear Headphones",
    description: "Reference-grade over-ears with planar magnetic drivers, plush memory-foam pads and 40h battery.",
    specifications: "Drivers: Planar magnetic\nBattery: 40h\nWeight: 280g",
    price: 18999, discount: 15, stock: 6, category: "Electronics", subCategory: "Audio",
    colors: ["Slate", "Ivory"], sizes: [],
    images: [img("photo-1583394838336-acd977736f90"), img("photo-1505740420928-5e560c06d30e")],
    rating: 4.7, ratingCount: 167, createdAt: now(),
  },
  {
    id: "p-22", vendorId: "u-vendor-1", vendorName: "Sunset Threads",
    name: "Saffron Maxi Dress",
    description: "Flowing maxi dress in saffron crepe with a cinched waist and bias-cut skirt. Effortless drape.",
    specifications: "Fabric: Crepe\nLining: Yes",
    price: 4799, discount: 22, stock: 14, category: "Fashion",
    colors: ["Saffron", "Slate"], sizes: ["S", "M", "L", "XL"],
    images: [img("photo-1539008835657-9e8e9680c956"), img("photo-1496747611176-843222e1e57c")],
    rating: 4.5, ratingCount: 51, createdAt: now(),
  },
];

export function ensureSeeded() {
  if (readKey<boolean>(KEYS.seeded, false)) return;
  writeKey(KEYS.users, DEMO_USERS);
  writeKey(KEYS.products, DEMO_PRODUCTS);
  writeKey(KEYS.orders, []);
  writeKey(KEYS.reviews, []);
  writeKey(KEYS.complaints, []);
  writeKey(KEYS.carts, {});
  writeKey(KEYS.otps, []);
  writeKey(KEYS.seeded, true);
}